### ISSUE TITLE
missing iife in xhook.js in dist folder 

### ISSUE THREAD

**Issue by fernandolguevara** [jpillora/xhook#67]
xhook.js in dist folder is not wrapped with an immediately  invoked function expression.

the code is replacing the native functions,
Ex:
[`
FormData = 'FormData';
`](https://github.com/jpillora/xhook/blob/gh-pages/dist/xhook.js#L34)

**Comment by fernandolguevara** [comment]
@jpillora

**Comment by morsdyce** [comment]
Sorry for the late response to this.
This was done initially because the IIFE that was generated by coffescript did not allow it to run on environments that do not support "window" such as ReactNative and Nativescript.

I however forgot about the assignment of FormData in that context thus made the mistake of it leaking into the window replacing the original implementation.

This has now been rectified and new 1.4.4 version released to amend this.

Thanks
