### ISSUE TITLE
responseXML is null

### ISSUE THREAD

**Issue by interface-master** [jpillora/xhook#86]
I'm including the library via
```import xhook from 'xhook';```
and not doing anything else with it (yet)

However, a call that used to work just fine retrieving an XML file, no longer works and throws an error:
```TypeError: XMLRequestObj.responseXML is null```

I've tried analyzing the requests, the responses, trying to bypass xhook for this XML call, and everything in between to no avail.
I believe there is an issue in the library that's not setting the XML response correctly.

**Comment by morsdyce** [comment]
Hey @interface-master I'll try to look into this soon.

Thanks for reporting this issue

**Comment by morsdyce** [comment]
After investigating this, it seems this is because of the browser not following the spec closely enough.

As stated in the spec: 
https://xhr.spec.whatwg.org/#the-responsexml-attribute

`If responseType is not the empty string or "document", then throw an "InvalidStateError" DOMException.`

Whenever we fetch an XML response the responseType seems to be an empty string and not "document" which is why responseXML is not filled with the parsed xml.

I'm looking into the option of adding the responseXML property even if we don't detect that this is an xml response to see if it doesn't affect other requests as we want to behave the same as browsers behave today to minimize these issues.

Will update soon on this matter

**Comment by morsdyce** [comment]
Fixed in 1.4.8
